name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compilar:
    # criar maquina virtual para usar no pipeline
    runs-on: ubuntu-latest

    steps:
    - name: fazer p git clone 
      uses: actions/checkout@v4
    
    - name: execultando primeiro comando 
      run: echo " Amo DEVOPS:)"
    
    - name: EXECULTANDO dois ou mais comandos
      run: |
        ls -l
        echo "fim do processo "
        

